forge 'https://forgeapi.puppetlabs.com'

mod '3fs-phantomjs', '1.0.0'
mod 'golja-gnupg', '1.2.3'
mod 'inkblot-hashicorp', '1.4.0'
mod 'maestrodev-maven', '1.4.0'
mod 'maestrodev-wget', '1.7.3'
mod 'puppet-archive', '2.3.0'
mod 'puppet-nodejs', '5.0.0'
mod 'puppetlabs-java', '2.1.0'
mod 'puppetlabs/stdlib', '4.21.0'
mod 'tracywebtech-pip', '1.3.4'
