---

- name: Publish the Docker image to repository
  hosts: all
  gather_facts: false
  connection: local

  tasks:
    - set_fact:
        images_name_suffix: "{{ '' if (image_type == 'base') else '-'+image_type }}"
    #
    - name: Get the current caller identity information
      aws_caller_info:
        region: "{{ aws.region }}"
      register: caller_info
      when: docker.repository.find('amazonaws.com') != -1

    - name: Login to repository for AWS ECR for pushing the Docker image
      shell: "aws ecr get-login-password --region {{ aws.region }} | docker login --username AWS --password-stdin {{ caller_info.account }}.dkr.ecr.{{ aws.region }}.amazonaws.com"
      args:
        executable: /bin/bash
      when: docker.repository.find('amazonaws.com') != -1

    - name: Publish the Docker image with version tag
      docker_image:
        name: "{{ docker.repository }}/{{ docker.image.name }}{{ images_name_suffix }}"
        tag: "{{ docker.image.version }}"
        source: local
        push: true

    - name: Publish the Docker image with latest tag
      docker_image:
        name: "{{ docker.repository }}/{{ docker.image.name }}{{ images_name_suffix }}"
        tag: latest
        source: local
        push: true
