---
name: Publish Docker Base
'on':
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
        with:
          ref: main
      - uses: docker/login-action@v4
        with:
          username: shinesolutions
          password: ${{ secrets.SHINEOPENSOURCE_GITHUB_TOKEN }}
      - uses: cliffano/command-docker-action@v2.1.0
        with:
          image: shinesolutions/the-works-buildenv:3.1.1
          shell: bash
          extra_args: '-v ~/.docker/config.json:/root/.docker/config.json:ro'
          command: |
            make clean deps lint build-docker-base &&
            cat logs/aem-platform-buildenv-base.log &&
            docker --version &&
            docker info  &&
            docker inspect shinesolutions/aem-platform-buildenv &&
            make publish-docker-base
